Add steps to set up a local development environment
bcgov/rsbc-digital-forms pull request #157
Opened 2023-08-11 22:35 UTC by SteveF4

Documented steps for new developers and testers to set up their own local development environment. Original task: [DF-2645](https://justice.gov.bc.ca/jirarsi/browse/DF-2645).

2023-08-15 16:14 UTC, amlanc1 requested changes
Added comments inline

2023-08-15 16:14 UTC, amlanc1 commented on DEVELOPER.md
> +    docker login --username default-be78d6-kqpjvc --password PASSWORD artifacts.developer.gov.bc.ca/dbe7-images
Similar to the Password, remove the actual username too. We dont need the username to be public too.

2024-05-27 20:53 UTC, adimar-aot submitted a review, later dismissed

2024-05-27 20:54 UTC, adimar-aot approved these changes

2024-05-27 20:54 UTC, merged